### ISSUE TITLE
Search functionality doesn't work when sorting by Release Date

### ISSUE THREAD

**Issue by codewithjess** [googleinterns/step110-2020#74]
As stated in the title, the search functionality is broken when the sort order is Release Date. It works fine for both Title sort orders.

**Comment by BryanTriana** [comment]
Yeah this is actually not a bug but a limitation. Datastore doesn't let me filter for items with two different properties with inequality operators. So if I sort based on release date, I can't search with the title.

**Comment by codewithjess** [comment]
https://cloud.google.com/appengine/docs/standard/java/datastore/query-restrictions

Can you do something similar to the query below, which is valid according to the docs:
```
Filter birthYearMinFilter =
    new FilterPredicate("birthYear", FilterOperator.GREATER_THAN_OR_EQUAL, minBirthYear);

Query q =
    new Query("Person")
        .setFilter(birthYearMinFilter)
        .addSort("birthYear", SortDirection.ASCENDING)
        .addSort("lastName", SortDirection.ASCENDING);
```
filter by title prefix, first sort by title, then sort by release date

**Comment by BryanTriana** [comment]
OK I am going to try it out once I finish the recommendation algorithm
