### ISSUE TITLE
Seeing duplicates of fav items in profile page

### ISSUE THREAD

**Issue by rharagutchi** [googleinterns/step110-2020#76]
A couple things:
- FavItemsDS should not allow adding duplicates
- FavItemsDS should return a set of items for a user
![duplicates](https://user-images.githubusercontent.com/65361383/88213172-368be380-cc0d-11ea-9c6e-a67950cfc31d.png)

**Comment by BryanTriana** [comment]
I think this issue is linked to this one: https://github.com/googleinterns/step110-2020/issues/71
If the like button is clicked very fast datastore doesn't seem to be able to check that the item is a duplicate. Will have to look for a way to prevent this.

**Comment by rharagutchi** [comment]
yea, I made the two issues to track the different fixes. One in the web client, and one in the backend

We should fix both to make the code as resilient as possible and not just resilient to just the current use cases as those can change a lot over time

**Comment by BryanTriana** [comment]
The backend now uses sets when working with favorite items and always checks if there is a duplicate. So this issue shouldn't be happening anymore.
